spring:
  application:
    name: mcc-account-service
  datasource:
    url: jdbc:mariadb://localhost:3306/i_account?useSSL=false&serverTimezone=UTC
    username: root
    password: '1469370'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 9091
feign:
  clients:
    customer:
      name: customer-service
      url: http://localhost:9090/customers

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,circuitbreakers"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

  timelimiter:
    instances:
      customerCircuitBreaker:
        timeout-duration: 5s